Set higher default and allow configuring puppeteer protocol timeout
meteortesting/meteor-browser-tests pull request #58
Opened 2024-07-23 20:46 UTC by make-github-pseudonymous-again

I believes this should fix https://github.com/Meteor-Community-Packages/meteor-mocha/issues/104.

2024-07-23 20:48 UTC, make-github-pseudonymous-again commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
The env var name and the default value are derived from similar functionality already present for the `nightmare` driver: https://github.com/Meteor-Community-Packages/meteor-browser-tests/blob/72df7ffd5d76633a8469dbe42726d22453c7d8a2/browser/nightmare.js#L44

2024-07-23 20:50 UTC, make-github-pseudonymous-again commented
@nachocodoner @jankapunkt @StorytellerCZ Will this require a backport to work in Meteor 2 or is the latest version compatible with both Meteor 2 and 3?

2024-07-23 22:17 UTC, jankapunkt commented
@make-github-pseudonymous-again it's intended to work with both but please let me know if you encounter issues.

2024-08-04 15:31 UTC, make-github-pseudonymous-again commented
@nachocodoner If that question is for me, I did not test anything. Just assumed it would work.

2024-12-09 21:42 UTC, make-github-pseudonymous-again commented
@nachocodoner How could I test this before merging it? I can reproduce this bug locally.

2024-12-11 02:17 UTC, StorytellerCZ commented
@make-github-pseudonymous-again create a `packages` folder in your app and in copy this package in there from the PR, that version will then take precedent.

2024-12-11 08:15 UTC, jankapunkt commented
@make-github-pseudonymous-again cab there be a situation where users might want to set `protocolTimeout` to `0`?

2024-12-11 12:22 UTC, make-github-pseudonymous-again commented
The `protocolTimeout` setting in `puppeteer` is a timeout that is applied to all registered connection message callbacks: if puppeteer does not get a message response within that time, then the connection is considered broken.

It seems the puppeteer driver is making puppeteer wait for a message response for the entire duration of the scheduled tests, which can easily reach in the minutes, especially for client app tests.

@jankapunkt `protocolTimeout = 0` would be interpreted as "no timeout" AFAICT. See:

  - https://github.com/puppeteer/puppeteer/blob/159513c8dbe2c9f51aa37dbe531d52b5daf1e106/packages/puppeteer-core/src/common/Connection.ts#L73-L82

Default is 3 minutes. See:

  - https://github.com/puppeteer/puppeteer/blob/159513c8dbe2c9f51aa37dbe531d52b5daf1e106/packages/puppeteer-core/src/common/Connection.ts#L202
  - https://github.com/puppeteer/puppeteer/blob/159513c8dbe2c9f51aa37dbe531d52b5daf1e106/packages/puppeteer-core/src/common/BrowserConnector.ts#L62-L67

2024-12-11 12:35 UTC, jankapunkt requested changes

2024-12-11 12:35 UTC, jankapunkt commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
@make-github-pseudonymous-again 

> protocolTimeout = 0 would be interpreted as "no timeout" AFAICT. See

In that case, your current code would never allow such, because 0 would be evaluated as falsy and thus always fall back to `TWENTY_DAYS`.

To also support 0 as value, it should be

```
protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) ?? TWENTY_DAYS,
```

2024-12-11 13:03 UTC, make-github-pseudonymous-again commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
Makes sense.

2024-12-11 13:06 UTC, make-github-pseudonymous-again commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
On the other hand, the intention behind twenty days here (copied from Nightmare's default) is perhaps to disable the timeout entirely. So should we instead have the default be `0` instead of `TWENTY_DAYS`?

2024-12-11 13:10 UTC, jankapunkt commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
@StorytellerCZ what do you think here?

2024-12-18 11:05 UTC, StorytellerCZ commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
I think `0` should disable timeout, I think that is the intention with this. If nothing is passed then use default.

2024-12-18 20:41 UTC, make-github-pseudonymous-again commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
OK. I'll update this PR to set "no timeout" as the default, which means passing `protocolTimeout = 0` to `puppeteer`.

2024-12-19 04:06 UTC, StorytellerCZ commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
That is not what I meant. From my understanding the default right now is `TWENTY_DAYS`, keep that if there is no input. If the input is something different, including `0`, then set it to that. So if the input is `0`, then timeout is zero = disabled.

2024-12-19 19:08 UTC, make-github-pseudonymous-again commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
OK. Had misunderstood. Will apply @jankapunkt's suggestion instead then.

2025-01-03 17:48 UTC, make-github-pseudonymous-again commented
> @make-github-pseudonymous-again create a `packages` folder in your app and in copy this package in there from the PR, that version will then take precedent.

@StorytellerCZ Just tested this. Works: setting a low timeout (5000ms) crashes mid-tests, setting a high timeout lets all tests run to completion. Setting a really low timeout (5ms) crashes during puppeteer setup.

Just out of curiosity, does it matter what name I give to the package under `packages/`? I named it `packages/meteortesting:browser-tests`.

Next step is to act on https://github.com/Meteor-Community-Packages/meteor-browser-tests/pull/58#discussion_r1891104026, and then I think it will be ready to merge.

2025-01-03 17:52 UTC, jankapunkt commented
The folder name is irrelevant as long as it contains the package.js file with proper package config

2025-01-03 17:56 UTC, make-github-pseudonymous-again commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
Suggestion applied.

2025-01-29 20:05 UTC, make-github-pseudonymous-again commented on browser/puppeteer.js
> +      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
@StorytellerCZ Waiting for your input.

2025-01-30 10:23 UTC, StorytellerCZ approved these changes

2025-02-13 12:42 UTC, jankapunkt approved these changes

2025-02-13 12:42 UTC, merged